### ISSUE TITLE
Make props animation

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#133]

**Comment by pausp1** [comment]
R4YL_ATREZZO_Medium_herb
R4YL_ATREZZO_Small_herb
R4YL_PROP_Arbol1

Create one loopeable animation for each one of this plants with blendshapes (leaves moved by the wind softly), ensure to bake the animation before exporting and that the pivot is on the minimum-center of the object.

**Comment by pausp1** [comment]
please, check the animations from the game assets
