### ISSUE TITLE
Model and texture boss

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#137]

**Comment by BravoXavi** [comment]
**[VERY IMPORTANT]**: Please, a person who does something CANNOT validate it. Make sure to wait for someone to validate things like the models BEFORE animating or doing advanced steps to avoid problems like bad pivots, scaling and rotations!

**Comment by pausp1** [comment]
Currently adding feathers and a leaves neckless, also some adjustes on the NM map should be done

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/38457477-1328d1b0-3a91-11e8-8004-0a42ec9dd01f.png)

![image](https://user-images.githubusercontent.com/32684237/38457478-21d9fd7e-3a91-11e8-9311-dda50863892d.png)

![image](https://user-images.githubusercontent.com/32684237/38457494-4018b82a-3a91-11e8-94f9-d4454343473b.png)

![image](https://user-images.githubusercontent.com/32684237/38457514-9a183058-3a91-11e8-9d9f-01ab179d83d6.png)

**Comment by Aenerida** [comment]
On the retopology there is something weird on the thumbs, i think is because the three polygons dont have smooth and the others have or maybe they need a bit more polygons there.

On the texture I would add more shadow on the eyes to make them more deep. Also, i think the leaves will be better as a 3d model than alpha.

**Comment by pausp1** [comment]
Thumbs: that is the uv cut, it needs to be there

I can add more shadow on the eyes

I prefer the alpha because it will be easier to animate with blendshapes (and I'll have to do that...)

About the gems, it's ok, I'll change it

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/38465484-86bec266-3b1c-11e8-9b58-77f847354098.png)

eyes and gems solved!

**Comment by pausp1** [comment]
https://drive.google.com/drive/folders/1dtUJzKrRh5Q7f8siOVddi3PshMdTzxaS?usp=sharing
