### ISSUE TITLE
Model and texture PJ

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#138]

**Comment by BravoXavi** [comment]
**[VERY IMPORTANT]**: Please, a person who does something CANNOT validate it. Make sure to wait for someone to validate things like the models BEFORE animating or doing advanced steps to avoid problems like bad pivots, scaling and rotations!

**Comment by martafm1** [comment]
![captura](https://user-images.githubusercontent.com/32684250/38453694-26737522-3a5a-11e8-9ba6-020192db1500.PNG)

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/38453698-32f7a0ca-3a5a-11e8-9005-96aba2ea709f.png)

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/38453702-40b06c42-3a5a-11e8-9578-1f961968089e.png)

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/38453705-4cad7daa-3a5a-11e8-92e9-ba6a53c6197c.png)

**Comment by pausp1** [comment]
It looks okay, before I validate it, can you send a wireframe override screenshot from booth sides please? Thks!!

**Comment by pausp1** [comment]
In this step we dont have to care about pivots and scales, but take care of them when you export the animated version, every character must be exported facing to the direction they move in-game

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/38454874-9f4b13be-3a6f-11e8-8822-257ed7a72ccd.png)
