### ISSUE TITLE
IGU

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#140]
-Ingame IGU
-Menus, buttons etc

**Comment by Aenerida** [comment]
![sin titulo](https://user-images.githubusercontent.com/32684259/38268067-7e42d444-377d-11e8-9d8d-3e1e2072d93b.png)
![sin](https://user-images.githubusercontent.com/32684259/38268080-8351a8e8-377d-11e8-9cea-808410ea3926.png)

**Comment by pausp1** [comment]
Buen trabajo! cuando lo tengas ponmelo para validar ;)

**Comment by Aenerida** [comment]
![options](https://user-images.githubusercontent.com/32684259/38496740-de53dfa6-3bfe-11e8-8ff1-73e617c8a930.png)
![options_blueball](https://user-images.githubusercontent.com/32684259/38496741-de6e9e90-3bfe-11e8-816e-7688f4d3568c.png)

**Comment by Aenerida** [comment]
![boss_normal](https://user-images.githubusercontent.com/32684259/38805381-ea37f510-4175-11e8-86ba-1a523d40bd27.png)
![reference](https://user-images.githubusercontent.com/32684259/38805382-ea51b8a6-4175-11e8-930d-fc90a4d0d222.png)
![time_line](https://user-images.githubusercontent.com/32684259/38805383-ea6d5980-4175-11e8-973c-38fc382aa7db.png)
![design](https://user-images.githubusercontent.com/32684259/38805392-eeb23498-4175-11e8-9ac7-355fbe14ec30.png)

**Comment by Aenerida** [comment]
![icon_traps_totem](https://user-images.githubusercontent.com/32684259/38869927-99c01afe-424c-11e8-9742-97dbe1d40520.png)
![range_attack](https://user-images.githubusercontent.com/32684259/38869928-99de81ce-424c-11e8-92b4-ff36676d1832.png)
![start](https://user-images.githubusercontent.com/32684259/38869929-99f630d0-424c-11e8-8ad0-5ed87ccbf7be.png)
![icon_punch](https://user-images.githubusercontent.com/32684259/38869930-9a13160a-424c-11e8-8c26-1d358e23186d.png)
![icon_trap_root](https://user-images.githubusercontent.com/32684259/38869931-9a2dc8d8-424c-11e8-98f3-19c3a4a1f7cf.png)
![icon_traps_death](https://user-images.githubusercontent.com/32684259/38869933-9a520586-424c-11e8-9ce1-2383acd634aa.png)
![icon_traps_slow](https://user-images.githubusercontent.com/32684259/38869934-9a6be9ec-424c-11e8-83ab-19493b5f5aea.png)
