### ISSUE TITLE
Model power ups

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#177]

**Comment by martafm1** [comment]
we need to redo the shield power up because don't seems to follow the artistic line

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39368944-3afb2814-4a3b-11e8-8240-a723ce76f678.png)
![image](https://user-images.githubusercontent.com/32684237/39368969-5218c27c-4a3b-11e8-88a8-3b6b9c234da0.png)
![image](https://user-images.githubusercontent.com/32684237/39369014-725d7564-4a3b-11e8-94bc-48f899e5ebfe.png)
![image](https://user-images.githubusercontent.com/32684237/39369086-a0fab8a0-4a3b-11e8-8839-2941aabd9751.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39370039-2b201348-4a3e-11e8-90c6-e5c9f674b45c.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39394345-83c9569c-4ad1-11e8-94e4-a388b99d7a8f.png)
![image](https://user-images.githubusercontent.com/32684237/39394353-9c7aae16-4ad1-11e8-9ca1-fbcd0bb96660.png)
![image](https://user-images.githubusercontent.com/32684237/39394366-c9d52b48-4ad1-11e8-93b2-294e2e5532b1.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39398768-ff58caf4-4b12-11e8-9fb8-56e3dc3fe00a.png)
![image](https://user-images.githubusercontent.com/32684237/39398773-111be46a-4b13-11e8-9402-e968ee24d8d3.png)
![image](https://user-images.githubusercontent.com/32684237/39398775-1a944b18-4b13-11e8-819d-bc0461bb7275.png)
