### ISSUE TITLE
UI in-game redesign

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#200]

**Comment by Aenerida** [comment]
![icon_trap_root](https://user-images.githubusercontent.com/32684259/39814012-11efa308-5393-11e8-8cc2-313a05a92b48.png)
![icon_traps_death](https://user-images.githubusercontent.com/32684259/39814013-120aa3b0-5393-11e8-9d49-173a6a5752ca.png)
![icon_traps_slow](https://user-images.githubusercontent.com/32684259/39814015-122be070-5393-11e8-88d4-a7c99f2b3ffd.png)
![icon_traps_totem](https://user-images.githubusercontent.com/32684259/39814018-1245fa0a-5393-11e8-817e-af2848ebf22c.png)
![lb_buttom](https://user-images.githubusercontent.com/32684259/39814020-125fe8ca-5393-11e8-8b1b-8e08b9961c7b.png)
![lt_buttom](https://user-images.githubusercontent.com/32684259/39814022-127b664a-5393-11e8-86a7-07fec51259ba.png)
![rb_buttom](https://user-images.githubusercontent.com/32684259/39814023-1298d144-5393-11e8-9249-2b1b320b4bba.png)
![rt_buttom](https://user-images.githubusercontent.com/32684259/39814024-12b5970c-5393-11e8-8584-b6f25dc41cad.png)

**Comment by Aenerida** [comment]
This issue will be re-open to keep fixing on the design of the buttoms D:
