### ISSUE TITLE
Particles: list of all particles of the game

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#203]

**Comment by BravoXavi** [comment]
https://docs.google.com/document/d/1dLfX7gfQSoECCliQTl8WkFMeIrcNw2imK2T21O3fJ-0/edit

I already did it. Please, take a look at the last page of the GDD with all the particles and try to think if some of them are not necessary or if I'm forgetting something. Notice the details about the "?" mark.

**Comment by pausp1** [comment]
I would discard tje following 3 particles:

Bounce over head (?)
Leaf bouncing (?)
Mushroom bouncing (?)

**Comment by pausp1** [comment]
Also I would add a little dust on runners stepping and I'd use the color of the boss boddy particles to diferenciate the 3 phases
