### ISSUE TITLE
Boss model and texturing completely?

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#207]

**Comment by pausp1** [comment]
We will have to talk about this, i don't think we have to do redo the boss, at least at this point

**Comment by martafm1** [comment]
Okey , in class we talked to the group to see what they think

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/39696267-87c9c074-51ed-11e8-86b4-55477704c09f.png)

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/39696289-962d181e-51ed-11e8-9acd-53bcad86bc46.png)

**Comment by pausp1** [comment]
Aparently looks good, let me validate it after check if the skeleton matches with the model :)

**Comment by martafm1** [comment]
the model is in Drive  /art/personajes
