### ISSUE TITLE
Retexture plant and tree

### ISSUE THREAD

**Issue by Aenerida** [HiddenLair/Run4YourLife#208]

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39405280-c1a4f60c-4ba2-11e8-8fbf-51272dabf658.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39405285-db045f5c-4ba2-11e8-9a70-fb55553f4b9c.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39423070-84bc7e1c-4c70-11e8-8ff2-f17cab4f5196.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39515819-7ea96080-4dfb-11e8-97b9-3e3375643e96.png)
