### ISSUE TITLE
Delete, rename and tidy art folder

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#213]
It's a mess.

Every day a cat dies in pain because of you 😢 😭

**Comment by BravoXavi** [comment]
Maybe for this delivery this can... "wait" a little bit more, but please guys, we need to tidy that thing. It's full of Material, Textures, Materials2, Textures_new, Boss, Boss_1, Boss_new2, RunnerTest, Background 1, 2, 3, ...

This needs to be structured and everything that it's not mandatory should be completely deleted. For example, we cannot have materials named Material#47 in one folder, a material for another prop in another different folder with the name R4YL_prop_xxx_xxx_xxx_DF, and a third material embeded inside an object. Focus on one standard and respect the structure, please... >-<
