### ISSUE TITLE
Generate unexisting elements of the scene

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#217]
On Phase 3, the players go up three times. This zones are surrounded by white walls. This white walls should be substituted by appropiate props for the scene.

**Do not worry about the big round rock (the one like Indiana Jones).** That thing will be deleted.

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/39959635-d06cae92-5614-11e8-81b2-b1f939b62574.png)

**Comment by pausp1** [comment]
This is not the final texture version ^^^^, is just for the 13-05-18 art meeting

**Comment by pausp1** [comment]
This issue is obsolete, I'm going to close it and move it to done
