### ISSUE TITLE
Rendering performance problems

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#222]
The game suffers performance spikes

![image](https://user-images.githubusercontent.com/32639021/39651175-2e7b9302-4feb-11e8-9053-f62ce569f81c.png)

![image](https://user-images.githubusercontent.com/32639021/39651193-38ba4e3a-4feb-11e8-9334-a9080148fdcb.png)

Something related to alpha rendering. It take 170 ms to render a frame. Completely unacceptable !!

**Comment by PereViader** [comment]
[frame spike.zip](https://github.com/HiddenLair/Run4YourLife/files/1975819/frame.spike.zip)

Profiler info.

Can be loaded to unity at profiler window to see this

**Comment by PereViader** [comment]
Have not managed to reproduce it again.

Please, test it on your systems and report whether it happens to you too or was just a one time spike,

**Comment by BravoXavi** [comment]
I couldn't find a spike as high as that, but except the small spikes created when selecting a Character on the selection screen and so, in the Game Scene, this was the closest to a worrying spike that I got:

![captura](https://user-images.githubusercontent.com/13509534/39662711-76fbb730-5066-11e8-838b-f2daabbe7a88.PNG)

This particular spike is created by one of our scripts. (Blue mark)
