### ISSUE TITLE
Repair ScaleTick script to make it non dependant on Time.timeScale

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#241]
Since this script is used in Pause time, timeScale is 0 and deltaTime cannot be used to calculate anything.

Option: Make an extra class to calculate the time by ourselves with Time.realTimeSinceStartup to use it in this cases.

**Comment by PereViader** [comment]
making an animation in code is harder than it need to be.

I would make it like we did with power ups.

A playable director that plays these actions
