### ISSUE TITLE
Particle: Trap Signaling

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#248]

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/40166734-936725dc-59bf-11e8-8eb1-80eecd2e09ef.png)

You can check the particles working in scenes/empty

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/40167346-1d921f4a-59c1-11e8-841b-b6785f73ecb0.png)

You can Check it in live in Scenes/empty

**Comment by pausp1** [comment]
https://drive.google.com/open?id=1MKO_HqRfixTtC_iHBnwGy67PnAgo53eM

**Comment by pausp1** [comment]
Btw, The circle from the picture had been changed, check the link^^^^
