### ISSUE TITLE
Particle: BOSS eyes

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#250]

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/40051985-eb46d9e8-583c-11e8-90e5-1f304ab88fdb.png)

the particles are aplyed on the boss in scene: scenes/sandbox/empty, check it from there

**Comment by pausp1** [comment]
https://drive.google.com/open?id=1MKO_HqRfixTtC_iHBnwGy67PnAgo53eM
