### ISSUE TITLE
Modeling and texturing the tiling objects of playable zone.

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#263]

**Comment by martafm1** [comment]
![image](https://user-images.githubusercontent.com/32684250/40267162-4b69a896-5b58-11e8-9c70-d036421cbd50.png)

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/40279545-87dededa-5c44-11e8-8103-02738afa658b.png)
Shall we smooth that edges a bit more?

**Comment by pausp1** [comment]
Also I thing that the tiles of the grass are too visible

**Comment by martafm1** [comment]
I change the texture of the ground and I delete the alpha zone

**Comment by BravoXavi** [comment]
![img_22052018_134718_0](https://user-images.githubusercontent.com/13509534/40360575-e2439f90-5dc6-11e8-9152-f69d60f34a27.png)

Please, follow this instructions in order to have the proper elements.
