### ISSUE TITLE
Particle: Boss normal shot 

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#264]

**Comment by pausp1** [comment]
https://drive.google.com/open?id=1MKO_HqRfixTtC_iHBnwGy67PnAgo53eM

**Comment by martafm1** [comment]
I like shoot particle, but the player's particles are weird, it can look better without any particles.

**Comment by pausp1** [comment]
The particles on players head is the shot impact particles, it is suposed to trigger when the shot colides somewere
