### ISSUE TITLE
URGENT: Define animation timmings

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#315]
Hi guys!
The following animation lengths needs to be specified (in seconds, please):
Boss: cast trap
Boss: initial scream
runner: electrocution
runner: initial scream
runner: double jump (voltereta)

It would be nice to have all this info before the weekend, if I forget any animation, please add it.
Thank you for your assistance :)

**Comment by BravoXavi** [comment]
Boss: cast trap -> 1.10 secs
Boss: initial scream -> 1 sec
runner: electrocution -> 0.5 sec (IMPORTANT: Fully loopeable)
runner: initial scream -> 0.5 sec (IMPORTANT: Fully loopeable)
runner: double jump (voltereta) -> 0.2 secs

Those are the timings :) Also, they're included on the GDD!

**Comment by pausp1** [comment]
Hi guys!

The boss animations are done and in the scene, i think that the cast animation is already implemented because I have animated over the old track, but check it just in case.

In theory you just need to implement te initial scream. By the way, "scream" is not loopeable, please blend it at end. If u need it to be loopeable make me know, it will be really fast
