### ISSUE TITLE
Need Traps Visual

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#320]
We need:
-Bomb(That can release fire on spheric area, and jump)
-Fire from bomb
-EarthPike, for this one we need 2 Models, 1 normal pike, and a triple Pike.
-Wall from earthPike
-Wind particles(static ones, which will be emited all over  the wind zone)
-Flying objects(still dont know what should be)
-Tornadoes(This may should be a particle system)
-Thunder(This one must go from the floor(impact point) to the sky)
-Electric trap

Those are the basics for traps,we will still need all efects to advise, start, and exit them(but not needed for this milestone maybe). For more info, contact with me, i will try to set some  sizes and definitions when someone accept  this task, or i've finished traps polish

**Comment by PereViader** [comment]
Try to make issues more granular.

This issue has too much work in it.
