### ISSUE TITLE
Delete .unitypackage from .gitignore

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#36]

**Comment by PereViader** [comment]
Why do we need to keep these files under version control?

**Comment by BravoXavi** [comment]
Artists wanted to upload some closed packages (eg. Boss). Should we just add all the separated assets without packages?

**Comment by PereViader** [comment]
From the documentation:

Select Import and Unity puts the contents of the package into the Assets folder, which you can access from your Project View.

We want the contents of the package stored. But why do we need to keep the package itself under version control?

We would be storing two times the same assets. One for the package, the other for the imported ones.

**Comment by PereViader** [comment]
When an artist wants to upload something to the project, they can make a package and import it to the project.

**Comment by PereViader** [comment]
We will not store them.
