### ISSUE TITLE
Design the GUI

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#37]
Design on PSD a well-looking interface for the "navegable"

**Comment by pausp1** [comment]
Mariangeles, adjunta una captura para que lo pueda validar pliis :)

**Comment by Aenerida** [comment]
![interface_ingame_notfinal_v2](https://user-images.githubusercontent.com/32684259/37242264-bb3cfaca-2466-11e8-8fbf-5318d6e56703.png)
![interface_menu_notfinal](https://user-images.githubusercontent.com/32684259/37242265-bb55fd18-2466-11e8-9e65-6a295f71b899.png)
![interface_pause_notfinal](https://user-images.githubusercontent.com/32684259/37242266-bb6dc8c6-2466-11e8-98e6-9e044edcbc03.png)

**Comment by Moaif** [comment]
Not valid GUI. we need to think how to make it more intuitive for players(Ingame)
