### ISSUE TITLE
Phase 2 Gem: Implement Particles and Effects

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#407]

**Comment by pausp1** [comment]
I'll generate the following particles related with the gem:

-Gem appears
-Gem idle
-Gem vanishes
-Fire for the top of the columns

If I'm missing something or any of you has any new idea make me know :)

**Comment by pausp1** [comment]
R4YL_PART_GEM_appear and R4YL_PART_GEM_idle are done in assets/prefabs/particles/instantiable

**Comment by pausp1** [comment]
R4YL_PART_GEM_vanish is done in assets/prefabs/particles/instantiable
