### ISSUE TITLE
Draw skybox/background

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#44]
We need at least one early version of the background for the "navegable" Don´t waste time looking for the perfect draw (maybe you can combine and compose internet images), Make sure the size of the draw matches with the size of the 3d scene

**Comment by Aenerida** [comment]
![background_preview_v2](https://user-images.githubusercontent.com/32684259/37538858-42161c58-2952-11e8-8e8b-a30ef841b5f7.jpg)

**Comment by pausp1** [comment]
cuando lo hayas metido en unity y veas q funciona puedes cerrar el issue y moverlo a done, pliss? graciaaas!
