### ISSUE TITLE
Redo spikes

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#449]
The spikes don't look deadly and scary.

With a single sight, you should be able to tell that they are there and ready to kill you.

**Comment by BravoXavi** [comment]
Also, be aware of the details of the spikes and the fact that the one on phase 3 should be a 3-pointed spike, in phase 2 should be wide enough to "hide" a wall inside it, the way that need to be destroyed, etc

**Comment by pausp1** [comment]
Is this to do duplicated with this one? https://github.com/HiddenLair/Run4YourLife/issues/539

**Comment by PereViader** [comment]
yes
