### ISSUE TITLE
Concept art Traps

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#45]
Design a animal-totem-based traps,
Que trampas tenemos? 4 en total!

**Explosión:** trampa que causa Muerte en un área circular.
**Raíz enredadera**: trampa que Enraíza a un solo objetivo, el cual ha de interactuar varias veces para liberarse.
**Cabezón maya**: trampa que causa Empujón en un área circular.(cabeza grande de piedra que grita)
**Trampa de ralentizamiento**:algun tipo de cepo que se pueda enganchar facilmente al corredor

**Comment by Aenerida** [comment]
![img_20180310_134116](https://user-images.githubusercontent.com/32684259/37242936-aff7ee76-2471-11e8-8e8f-6dce72ba71c8.jpg)
![img_20180310_143804](https://user-images.githubusercontent.com/32684259/37242937-b01106e0-2471-11e8-8fdb-c950b47d33c4.jpg)
![img_20180310_144014](https://user-images.githubusercontent.com/32684259/37242938-b02acd3c-2471-11e8-9727-f98364aa986b.jpg)
![img_20180310_143746](https://user-images.githubusercontent.com/32684259/37242939-b04295a2-2471-11e8-9527-78ada910439a.jpg)

Comento, el primer concept es el del totem, tiene como cara de pena y cuando te acercas pues pone cara de loco, pega el grito y adios.

El segundo seria el de raiz enredadera; manos de golem que están abiertas y cuando pasas se cierran y te enganchan (quizás deberían estar un poco más abiertas)

El tercero es el de trampa de ralentizamiento; cuando el personaje toca la planta ésta explota y le cae pringue encima al personaje, de ahí que se ralentice.

El cuarto es la explosion; especie de planta con pinchos que al entrar en contacto con ella revienta e insta muerte.

He intentado equilibrar entre trampas, dos naturales y dos tipo totem, para que tuvieran un poco de coherencia.

**Comment by Aenerida** [comment]
![img_20180310_195711](https://user-images.githubusercontent.com/32684259/37245784-ab9bcc5e-249d-11e8-922b-d00c738e34f7.jpg)
![img_20180310_195717](https://user-images.githubusercontent.com/32684259/37245785-abb48b72-249d-11e8-8974-2b04de39c520.jpg)
![img_20180310_195724](https://user-images.githubusercontent.com/32684259/37245786-abcd639a-249d-11e8-8410-38af59e9acde.jpg)
![img_20180310_195649](https://user-images.githubusercontent.com/32684259/37245787-abe62146-249d-11e8-8d7e-412dade3d0fb.jpg)

**Comment by pausp1** [comment]
Perfecto!
