### ISSUE TITLE
model and texture 2 floor plattaforms

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#48]

**Comment by martafm1** [comment]
![thick plaform](https://user-images.githubusercontent.com/32684250/37203953-ba77cf8e-238f-11e8-8e1f-68f464c74ffd.JPG)

**Comment by pausp1** [comment]
Perfecto, Pal github! ;)

**Comment by martafm1** [comment]
![thick plaform](https://user-images.githubusercontent.com/32684250/37205221-4364fcc8-2394-11e8-882f-7008af552fa4.JPG)

**Comment by pausp1** [comment]
Pal github todo! <3
