### ISSUE TITLE
Implement phase 2 boss explosive bullet particles

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#485]
![image](https://user-images.githubusercontent.com/32639021/42806834-988ab31a-89af-11e8-9e74-cccfc3d22ca1.png)

**Comment by PereViader** [comment]
Pau said that the particles are done.

For any questions regarding them ask him.

**Comment by PereViader** [comment]
[18:37, 22/7/2018] Pau Master: Se llaman shot y impact creo
[18:38, 22/7/2018] Pau Master: Osea todo el rollo de ...Part_phase2_boss_ shot o algo así

**Comment by pausp1** [comment]
Boss_phase2_shot and boss_phase2_shot impact find it on assets/prefabs/particles
