### ISSUE TITLE
Change how dynamic objects parenting works.

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#509]
When the boss places a skill (Spike, Bomb) the skill gameobject's is reparented to the stage.

This makes it hard for the pool to retrieve it and makes the object confused about it's state (it thinks it is destroyed, but it is in reality active).

Instead of reparenting, make the skill use SimulateChildOf class to simulate it's parenting behaviour.
Look at the parent state and when it is destroyed, destroy the skill.

**Comment by BravoXavi** [comment]
Phase 1, 2 and 3 Bombs are now parented using SimulateChildOf
Phase 1, 2 and 3 Spikes are now parented using SimulateChildOf

No skills from the boss move from the pool when summoned on the scene.
