### ISSUE TITLE
Remove old platform go through asset

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#512]
It still exist in the asset folder and it can be found beeing used in the 3rd phase

**Comment by Moaif** [comment]
We have not a "finished" go throught platform, so its useless to change it now, if we will have to change it again

**Comment by BravoXavi** [comment]
I substituted anyway the assets in the gameScene and deleted the old unused ones so, in case that we just add scripts or change slightly the graphics, all is the same prefab
