### ISSUE TITLE
Move mushroom pivot to the base

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#523]
![image](https://user-images.githubusercontent.com/32639021/43512659-f7236408-957b-11e8-8bd1-0def25e94b06.png)

Make sure that the animation plays properly with the new location

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/43676176-149eb6b4-97ec-11e8-9a1f-ee279a5cdf8b.png)

Hi, This is done, please, note that the object has suffered a displacement due the pivot displacement and needs to be recolocated.
Please, close this issue once the mushroom is in place

**Comment by pausp1** [comment]
The mushroom is replaced.
Because of the pivot adjustments, the mushroom needs to be recolocated anyway:
![image](https://user-images.githubusercontent.com/32684237/43678479-3f3f0ffe-9814-11e8-9b75-18856e3c56e8.png)

**Comment by pausp1** [comment]
Hi!
It's solved, it was because of the blendshape reeimporting, i've tested and it works normaly, please check it and validate and close thus issue
Regards y besitos

**Comment by PereViader** [comment]
Works as expected
