### ISSUE TITLE
Main menu (Logotype)

### ISSUE THREAD

**Issue by Aenerida** [HiddenLair/Run4YourLife#529]
Please, re implement the logo at the main menu

![issue](https://user-images.githubusercontent.com/32684259/43538483-7740916a-95c2-11e8-9e8c-05c2d0c7d604.png)
![fondo main menu_v4](https://user-images.githubusercontent.com/32684259/43538605-c63284ae-95c2-11e8-991b-90e7c81b2b05.jpg)

**Comment by PereViader** [comment]
Soy de la opinión que me gusta mas sin el logo.

Queda una UI más minimalista y limpia.

Si hacemos que el background sea más dinámico con elementos móviles no hace falta llenar la pantalla para darle interés.

**Comment by martafm1** [comment]
En mi opinión sin el logo queda muy vacío. Pero si hay elementos detrás moviéndose no se notaría tanto que esta muy vacío y plano.

**Comment by pausp1** [comment]
Me gusta sin el logo, pero si se quita, creo q hay q poner más nubes, aparte de q se muevan
