### ISSUE TITLE
Thunder skill may not play

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#535]
As seen on this video at 0:40

https://photos.app.goo.gl/iZPjw9bw7uevhsAo8

The thunder visuals may not play properly.

**Comment by Moaif** [comment]
Could not reproduce  this bug, if you find again, please post the steps to do it.

**Comment by BravoXavi** [comment]
I also remember seeing this bug in the past, but I could not reproduce it again :(
