### ISSUE TITLE
Change double jump particle

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#544]
The particle movement is "horizontal" but the runner moves diagonally after double jumping.

Make a particle that moves diagonally or downwards. Decide depending on which looks better.

**Comment by pausp1** [comment]
I've changed the alignment to 45º, the efect donwards is not so good, here you have the result: (check the last seconds of the video)
https://drive.google.com/open?id=165oHYda-XmBS3-GJcy3w54gW9w8QbC9X
