### ISSUE TITLE
Make boss win animation

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#548]
Just like we have a dance animation in runners win, make an animation for the boss where it is dancing.

Go wild.

**Comment by pausp1** [comment]
We should discuss this in the next meeting, I don´t feel like the boss should dance if he is a "bad guy"... we can think an other animation toguether.

**Comment by PereViader** [comment]
Has this been discussed?

**Comment by pausp1** [comment]
Yes, its in progress

**Comment by pausp1** [comment]
Hi guys, 
The clip is done and uploaded, please proceed with the implementation
