### ISSUE TITLE
Implement particles for leaf platform go through action

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#554]
![image](https://user-images.githubusercontent.com/32565030/43824546-967fd4c0-9af2-11e8-9516-7e567400c98d.png)

Particles should not be distractive, so maybe a light particle system would fit.

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/43844917-1382852a-9b2b-11e8-9d65-403c9fb23dcf.png)

This is done, you can find it on assets/prefabs/particles/instantiable/R4YL_PART_Leaf_platform
Please, implement it in-game
