### ISSUE TITLE
implement particle for  phase3 bomb jump

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#556]
This could be like the "bounce" particle, but more visual(you cant see this one under the bomb, to light) also it should be more like the bomb, in order to associate that particle with it.

**Comment by pausp1** [comment]
the particle is done, you can find it on assets/prefabs/particles/instantiable/R4YL_PART_bomb_jump, please implement it in game

**Comment by Moaif** [comment]
Particles should be more visibles,  i'll wait to next iteration to implement them

**Comment by pausp1** [comment]
ok, I'm going for it

**Comment by pausp1** [comment]
I've changed the color and make the wave a bit bigger, you can try again
