### ISSUE TITLE
Sound to change/revise

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#557]
- [x] shield

- [x] coconut

- [x] Boss shout

Boss growl(removed)

- [x] Boss Capture runners(maybe cut it, 3s of clip, but 2s are empty)

- [x] Boss cast(modify this one for phase 2-3, use the same, but with a little difference in power or something)

- [x] Boss shoot phase 2

- [x] Boss mele phase 2

- [x] Boss mele phase 3

- [x] Bomb trapfall

- [x] Bomb jump

- [x] Bomb fire

- [x] Wind static sound

- [x] Runner second jump

**Comment by PereViader** [comment]
Changed second jump

**Comment by BravoXavi** [comment]
Boss_CaptureRunners sound cutted and cleaned spiky frequencies (New commit, forgot to add #557, soz)
