### ISSUE TITLE
Make spawn particle for earth spike

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#567]
https://photos.app.goo.gl/kHNdrss5bqyCbjLc6

The particle duration should be 1 second.

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/43843520-0dfad5e2-9b28-11e8-8cc2-dc8da2ccd134.png)
After try 1 second duration I saw that it was too short because the spike was still moving when the particle finished so I set the duration to 2 seconds, the timming looks good in game
