### ISSUE TITLE
Implement boss  hand particles that will color change depending on the skill cast

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#572]

**Comment by pausp1** [comment]
The particles are ready, I've created 3 p.system working toguether, all of them has the starting color as red, please, modify the start color parameter on each of the 3 p.systems in order to adapt the particles to the skill casted in that moment (red, blue...)

**Comment by Moaif** [comment]
I've scaled  particles x3 for phase 1, and x6 for phase 2/3, if you want to change them someway, at least respect those sizes, not in scale, but size,
