### ISSUE TITLE
Model and texture sign for dash and leaf platform

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#584]
As we agreed in the last meeting, we need to model a wooden sign to indicate how to break the wall and how to traspass the platform so we need one object with 2 DM

**Comment by PereViader** [comment]
Make a single 3d model of a sign and different textures for each of the types of sign.

Don't change the color or anything just the glyphs that teach.

Before making the different textures, give us different glyphs to chose from.

We will then choose one glyph for each one and you will then procede with making the texture.

Make the glyps as simple to understand as possible. 

Go through platform glyph examples:

![image](https://user-images.githubusercontent.com/32639021/44037227-1454f964-9f14-11e8-977a-7f5db81962f0.png)

**Comment by pausp1** [comment]
![screen2](https://user-images.githubusercontent.com/32684237/44198922-f9766700-a142-11e8-8fdb-b72929a6838f.jpg)
![screen1](https://user-images.githubusercontent.com/32684237/44198923-fa0efd80-a142-11e8-9639-057a860f7767.png)

At the moment I leave it like this, feel free to adjust the positions, please, note that the arrow sign is placed in a area with shadows, maybe we can add some self ilumination in the material or some "aceitito"
