### ISSUE TITLE
{To discuss on reunion}EarthSpike shards should spawn particles instead of fade

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#589]
We have tested to fade the earthspike shards, in order to make them dissapear gradually, but it's not posible, we  have the same problem that with the old traps and the transparent shader, we see through them, so we suggest to do a particle fade out instead

**Comment by PereViader** [comment]
We can't make it fade easily so yes. Making them disappear suddenly looks bad.

**Comment by BravoXavi** [comment]
A small particle system that hides the disappearing and helps seeing some kind of "fade" for the shards sounds good to me too.
