### ISSUE TITLE
{To disscus}Tornados should have sound?

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#590]
We  have tested tornados with sound, and they are a little invasive, meanning that as they spawn more than one at time, the sound is acumulated, and it may be anoying. So we have to think if its worth trying to find a sound not invasive even if we have more than 1 at time(they scale, cause they are 3D), or better do not have tornado sound.

(Add tornado sound to wind is not good, the wind itself do not grow in streght, but it sound like. And is not good, cause the tornados start with a delay from the wind screen fill, and they dont dissapear after the wind stop, they are there longer, so its nor right to set their sound to the wind, it does not fit).

**Comment by PereViader** [comment]
I would not give tornadoes sound. Wind + tornadoes is a going to be really loud.

**Comment by Moaif** [comment]
Tornados will not have sound.
