### ISSUE TITLE
Phase 3 Bomb - Raycast to check the floor is faulty

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#592]
When you cast the boms, it throws a ray and checks where is the floor under it. If the floor gets modified after the check is done, the bomb will disappear/stop on an unexisting area.

For example, on phase 1 cast Earth spike and then instantly the bomb on top of it, or in the zone when the platforms ar going up and down, cast a bomb just UNDER a platform going down (the bomb will trespass it, due to the object thinking that the floor is another platform).

**Comment by Moaif** [comment]
Already solved
