### ISSUE TITLE
Make icon for the game

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#596]
We need to make an icon for the game.

![image](https://user-images.githubusercontent.com/32639021/44198785-8ff65880-a142-11e8-9a55-86934474760f.png)

It's very important that we give a good impression from the start

**Comment by PereViader** [comment]
Custom Icon reslution should be

1024 x 1024

![image](https://user-images.githubusercontent.com/32639021/44198958-1743cc00-a143-11e8-93eb-5e13c62aa9cd.png)

**Comment by pausp1** [comment]
Pere, if this icon won't be bigger than this: 
![image](https://user-images.githubusercontent.com/32684237/44617330-98484500-a860-11e8-99bf-834b5a0daf20.png)
I don't think that we need a 1024x1024 size, with 256x256 should be enough, and we will save memory. For giving you a reference, most of the texture images of our game are 512x512.
