### ISSUE TITLE
Replace the floor spikes

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#609]
![44297530-79cbd200-a2d3-11e8-9ed4-a4e682b788cc](https://user-images.githubusercontent.com/32684237/44297713-6a9a5380-a2d6-11e8-94c4-3c164ba0e06c.png)
You can find it on assets/art/interactuables/spikes/R4YL..._spikes_new

**Comment by PereViader** [comment]
It's already done #607
