### ISSUE TITLE
Reduce particle count

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#663]
In order to cull the particle systems and not waste so many cpu cicles on particles, we need to make the particles procedural.

Follow the advice of this article provided by unity.

https://blogs.unity3d.com/es/2016/12/20/unitytips-particlesystem-performance-culling/

**Comment by pausp1** [comment]
Most of the particles are procedural, only the ones that leave trails like the boss, or the shooting plant etc are on world simulation space, others are local.

**Comment by PereViader** [comment]
Instead of having to redo all the particles I have done a pice of code to custom cull the particles

![image](https://user-images.githubusercontent.com/32639021/45174292-c2a7e400-b20a-11e8-939c-d1f3873fa49f.png)

The particles will only be played while the camera frustrum can see the spheres.
We will have to specify the radius of the sphere so that the particle fits inside the sphere

**Comment by pausp1** [comment]
![image](https://user-images.githubusercontent.com/32684237/45206347-15be7d00-b285-11e8-85ca-81db26f56f90.png)
Hi! This is the rework of the boss p.sistems (eyes, smoke and hip smoke) this are the changes:
-**20-30% less particles** on each system (more or less)
-**No noise** used

I've Uploaded the particles prefabs saved on:
 assets/prefabs/particles/decoration/R4YL_PART_boss_smoke_hip
 assets/prefabs/particles/decoration/R4YL_PART_boss_smoke
 assets/prefabs/particles/decoration/R4YL_Particles_Boss_eye

But somehow, the prefabs attached to the boss on gamescene doesn't get updated, maybe it is using an other copy of the prefabs? Please, could you check this and replace them manually? please, report me if this changes improve the performance

I start working with the waterfall particles now

**Comment by pausp1** [comment]
Hi again,
![image](https://user-images.githubusercontent.com/32684237/45207780-40123980-b289-11e8-96be-f56e5d2edebb.png)

The waterfall is done, the sistem that was emmiting more was the splash above, it had 150 active particles, now 40, also I've reduced the particles of the "espuma" below the waterfall to the half with no significant changes. I've reduced the waves from 15 to 10 too.

**Comment by PereViader** [comment]
Each runner ghost uses 60 particles lower the number of particles to 30 or under if possible.

**Comment by pausp1** [comment]
Done, is using 25 now, please, check if needs implementation, I've modified the prefab in assets/art/characters/ghost

**Comment by pausp1** [comment]
The fog is done, please, check if there is any improvement
