### ISSUE TITLE
Implement Traps behaviour

### ISSUE THREAD

**Issue by BravoXavi** [HiddenLair/Run4YourLife#70]
Implement the effects caused by traps (Explosion/Death, Impact, Root, Slow)

**Comment by BravoXavi** [comment]
@PereViader , about the behaviour of the impact (push) trap: How should we implement the movement? Activating and Deactivating physics or faking them with the actual simulated physics?

**Comment by PereViader** [comment]
I am not sure, which will be the best way to deal with this.
As I am not sure, I would do it using the rigidbody.

Start enabling the rigidbody and disabling the charactercontroller.

Then disable the isKinematic and give it some force.
When the force should end, set things back as they were.
