### ISSUE TITLE
Model+texture rocker platform

### ISSUE THREAD

**Issue by martafm1** [HiddenLair/Run4YourLife#86]

**Comment by martafm1** [comment]
![thick plaform](https://user-images.githubusercontent.com/32684250/37146831-3047a80e-22c5-11e8-8c8e-3ecbab4318a5.JPG)

**Comment by pausp1** [comment]
Están separados por piezas la plataforma y el chisme vertical? los programadores van a necesitar que sean 2 objetos separados para moverlo. Si ya está separado puedes cerrar la issue y ponerla en done :)

**Comment by martafm1** [comment]
La tuerca y la plataforma están separadas para que se pueda realizar la animación de rotación

**Comment by pausp1** [comment]
También que los pivotes de cada pieza estén en el  sitio sobre el que tengan que rotar

**Comment by martafm1** [comment]
los pivotes ahora los miro, no estoy segura

**Comment by pausp1** [comment]
okey, cuando estes segura ya lo puedes subir a github. cierra este issue y ponlo en done pliss

**Comment by martafm1** [comment]
vale
